use_frameworks!

platform :ios, '10.0'

target 'GLCommonComponent_Example' do
  pod 'SnapKit', '~> 5.6.0'
  pod 'GLCommonComponent', :path => '../'

  target 'GLCommonComponent_Tests' do
    inherit! :search_paths

    
  end
end
